/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkHubRouteImport } from './routes/work.$hub'
import { Route as WorkHubSlugRouteImport } from './routes/work.$hub.$slug'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkHubRoute = WorkHubRouteImport.update({
  id: '/$hub',
  path: '/$hub',
  getParentRoute: () => WorkRoute,
} as any)
const WorkHubSlugRoute = WorkHubSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkHubRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work': typeof WorkRouteWithChildren
  '/work/$hub': typeof WorkHubRouteWithChildren
  '/work/$hub/$slug': typeof WorkHubSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work': typeof WorkRouteWithChildren
  '/work/$hub': typeof WorkHubRouteWithChildren
  '/work/$hub/$slug': typeof WorkHubSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work': typeof WorkRouteWithChildren
  '/work/$hub': typeof WorkHubRouteWithChildren
  '/work/$hub/$slug': typeof WorkHubSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/work'
    | '/work/$hub'
    | '/work/$hub/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/work' | '/work/$hub' | '/work/$hub/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/work'
    | '/work/$hub'
    | '/work/$hub/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$hub': {
      id: '/work/$hub'
      path: '/$hub'
      fullPath: '/work/$hub'
      preLoaderRoute: typeof WorkHubRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/$hub/$slug': {
      id: '/work/$hub/$slug'
      path: '/$slug'
      fullPath: '/work/$hub/$slug'
      preLoaderRoute: typeof WorkHubSlugRouteImport
      parentRoute: typeof WorkHubRoute
    }
  }
}

interface WorkHubRouteChildren {
  WorkHubSlugRoute: typeof WorkHubSlugRoute
}

const WorkHubRouteChildren: WorkHubRouteChildren = {
  WorkHubSlugRoute: WorkHubSlugRoute,
}

const WorkHubRouteWithChildren =
  WorkHubRoute._addFileChildren(WorkHubRouteChildren)

interface WorkRouteChildren {
  WorkHubRoute: typeof WorkHubRouteWithChildren
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkHubRoute: WorkHubRouteWithChildren,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
